# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170706_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderpic',
            name='img',
            field=models.ImageField(default='uploads/blog/images/default.jpg', upload_to='', verbose_name='首页图片670x280'),
        ),
    ]
