# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170706_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(default='uploads/blog/images/default.jpg', upload_to='uploads/blog/images/', verbose_name='文章标头图片245x200'),
        ),
    ]
